-- ─────────────────────────────────────────────
-- NSE Corporate Actions Tracker — Database Schema
-- ─────────────────────────────────────────────

-- Raw corporate actions fetched from NSE
CREATE TABLE IF NOT EXISTS corporate_actions (
    action_id       SERIAL          PRIMARY KEY,
    symbol          VARCHAR(20)     NOT NULL,
    company_name    VARCHAR(100),
    action_type     VARCHAR(30)     NOT NULL,    -- dividend | split | buyback | rights | bonus
    ex_date         DATE,
    record_date     DATE,
    details         TEXT,
    fetched_at      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (symbol, action_type, ex_date)        -- prevent duplicate inserts
);

-- Watchlist of stocks to monitor
CREATE TABLE IF NOT EXISTS watchlist (
    symbol          VARCHAR(20)     PRIMARY KEY,
    company_name    VARCHAR(100),
    priority        VARCHAR(10)     DEFAULT 'normal' CHECK (priority IN ('high', 'normal')),
    added_at        TIMESTAMP       DEFAULT CURRENT_TIMESTAMP
);

-- Daily alert records generated by the tracker
CREATE TABLE IF NOT EXISTS alert_log (
    alert_id        SERIAL          PRIMARY KEY,
    alert_date      DATE            NOT NULL,
    symbol          VARCHAR(20)     NOT NULL,
    action_type     VARCHAR(30)     NOT NULL,
    ex_date         DATE,
    days_until      INTEGER,                     -- days between alert_date and ex_date
    priority        VARCHAR(10),
    generated_at    TIMESTAMP       DEFAULT CURRENT_TIMESTAMP
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_actions_symbol   ON corporate_actions(symbol);
CREATE INDEX IF NOT EXISTS idx_actions_ex_date  ON corporate_actions(ex_date);
CREATE INDEX IF NOT EXISTS idx_actions_type     ON corporate_actions(action_type);
CREATE INDEX IF NOT EXISTS idx_alerts_date      ON alert_log(alert_date);
